#!/bin/bash

(
wine  /home/juergen/ZiLOG/ZDSII_eZ80Acclaim\!_5.3.4/bin/make -C Z:\\workspace\\Debug  -f ez80FreeROS_Debug.mak $@ &
)  | sed -e 'y/\\/\//' -e 's#Z:#/home/juergen/Zilog#g' -e 's/\W\+(\([0-9]\+\),\([0-9]\+\))\W\+/:\1:\2:/g' -e 's/ERROR/ Fehler:/g' -e 's/WARNING/ Warnung:/g'
